apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
    inputs:
      art-id:
        type: string
        default: f65fc73e-c2e7-4153-9337-0046be60510b 


jobs:
  build:
    steps:
      - uses: cloudbees-io/get-artifact-details@v1
        with:
          artifact-id: f65fc73e-c2e7-4153-9337-0046be60510b  
      - uses: cloudbees-io/get-artifact-details@v1
        with:
          artifact-id: ${{ inputs.art-id }}           
