apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  build-art1:
    steps:
      - uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "art1-fe"
          version: "${{ inputs.version }}"
          url: "docker.io/MyApp/art1-fe:${{ inputs.version }}"
      - uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "art1-be"
          version: "${{ inputs.version }}"
          url: "docker.io/MyApp/art1-be:${{ inputs.version }}"