apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  build-art1:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: "f65fc73e-c2e7-4153-9337-0046be60510b"
          target-environment: "dev"
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: "6245fae7-065c-4fdc-b0bb-bdaac5f59a39"
          target-environment: "dev"