apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        default: str
      environment:
         type: string
         required: true  
         default: str2
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  

jobs:
  deploy-app1:
    steps:
      - name: Deploy art1-fe
        if: ${{ fromJSON(inputs.manifest).art1-fe.deploy }}
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "art3 version: ${{ fromJSON(inputs.manifest).art1-fe.version }}"
          echo "url: ${{ fromJSON(inputs.manifest).art1-fe.url }}"
          echo "env: ${{ inputs.environment }}"

      - name: Deploy art1-be
        if: ${{ fromJSON(inputs.manifest).art1-be.deploy }}
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "art3 version: ${{ fromJSON(inputs.manifest).art1-be.version }}"
          echo "url: ${{ fromJSON(inputs.manifest).art1-be.url }}"
          echo "env: ${{ inputs.environment }}"
