apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  

jobs:
  deploy-app1:
    steps:
      - name: Deploy art1-fe
        if: ${{ fromJSON(inputs.manifest).art1-fe.deploy }}
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: "${{ fromJSON(inputs.manifest).art1-fe.id }}"
          target-environment: "${{ inputs.environment }}"
      - name: Deploy art1-be
        if: ${{ fromJSON(inputs.manifest).art1-be.deploy }}
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: "${{ fromJSON(inputs.manifest).art1-be.id }}"
          target-environment: "${{ inputs.environment }}"
