apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        default: str
      environment:
         type: string
         required: true  
         default: str2
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  

jobs:
  deploy-app1:
    steps:
      - name: Deploy art1-fe
        if: ${{ fromJSON(inputs.manifest).art1-fe.deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "art1-fe"
          version: "${{ fromJSON(inputs.manifest).art1-fe.version }}"
          url: "${{ fromJSON(inputs.manifest).art1-fe.url }}"
          target-environment: "${{ inputs.environment }}"
      - name: Deploy art1-be
        if: ${{ fromJSON(inputs.manifest).art1-be.deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "art1-be"
          version: "${{ fromJSON(inputs.manifest).art1-be.version }}"
          url: "${{ fromJSON(inputs.manifest).art1-fe.url }}"
          target-environment: "${{ inputs.environment }}"
