apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  run-without-env:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world. Prop3 value: ${{ vars.prop3 }}"
  run-on-us-env:
    environment: us-env
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world. Prop3 value: ${{ vars.prop3 }}"
  run-on-us-env2:
    environment: us-env2
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world. Prop3 value: ${{ vars.prop3 }}"
