apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://esolang/jq:latest
        shell: sh
        run: |
          URL=${{ cloudbees.api.url }}/reserved/v1/delete-old-artifacts
          echo "`date` - Calling: $URL"
          curl -X DELETE --max-time 120 -H "Authorization: Bearer ${{ cloudbees.api.token }}" "$URL"
          echo "`date` - Done"