apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test API workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      param1:
        default: foo
        type: string
      param2:
        default: bar
        type: string
        
jobs:
  test:
    steps:
      - name: Call API
        uses: https://github.com/urvashisingh/try-api-action
        with:
          http-method: post
          uri: v2/workflows/runs/artifactinfos
          payload: '{ "runId": "${{ cloudbees.run_id }}", "runAttempt": "${{ cloudbees.run_attempt }}", "name": "art1", "url": "art1-url", "version": "1.0"}'
  publish:
    steps:
      - uses: cloudbees-io/publish-evidence-item
        name: Test publish-evidence-item action
        id: testAction
        with:
          content: test
